[versions]
bom = "2023.09.01"
compiler = "1.5.3"

[libraries]
bom = { module = "androidx.compose:compose-bom", version.ref = "bom" }

animation = { module = "androidx.compose.animation:animation" }
animation-graphics = { module = "androidx.compose.animation:animation-graphics" }
foundation = { module = "androidx.compose.foundation:foundation" }
foundation-layout = { module = "androidx.compose.foundation:foundation-layout" }
material = { module = "androidx.compose.material:material" }
material-icons-core = { module = "androidx.compose.material:material-icons-core" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
material-ripple = { module = "androidx.compose.material:material-ripple" }
material3 = { module = "androidx.compose.material3:material3" }
material3-windowsizeclass = { module = "androidx.compose.material3:material3-window-size-class" }
runtime = { module = "androidx.compose.runtime:runtime" }
runtime-livedata = { module = "androidx.compose.runtime:runtime-livedata" }
runtime-rxjava2 = { module = "androidx.compose.runtime:runtime-rxjava2" }
runtime-rxjava3 = { module = "androidx.compose.runtime:runtime-rxjava3" }
runtime-saveable = { module = "androidx.compose.runtime:runtime-saveable" }
ui = { module = "androidx.compose.ui:ui" }
ui-geometry = { module = "androidx.compose.ui:ui-geometry" }
ui-graphics = { module = "androidx.compose.ui:ui-graphics" }
ui-test = { module = "androidx.compose.ui:ui-test" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-text = { module = "androidx.compose.ui:ui-text" }
ui-text-googlefonts = { module = "androidx.compose.ui:ui-text-google-fonts" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-data = { module = "androidx.compose.ui:ui-tooling-data" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
ui-unit = { module = "androidx.compose.ui:ui-unit" }
ui-util = { module = "androidx.compose.ui:ui-util" }
ui-viewbinding = { module = "androidx.compose.ui:ui-viewbinding" }

# Not meant to be used and is just here for automatic updates
compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compiler" }
