[versions]

catalogs-plugins = "2023.11.18"
coil = "2.5.0"
composeicons = "1.1.0"

fresco = "3.1.3"

glide = "4.16.0"

javapoet = "1.13.0"

kotlinpoet = "1.15.0"
kotpref = "2.13.2"
kradle = "1.0.7"

landscapist = "2.2.12"
lottie = "6.2.0"

[libraries]
catalogs-androidplugins = { module = "io.github.lyxnx.gradle.android:android-plugins", version.ref = "catalogs-plugins" }

coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

composeicons-cssgg = { module = "br.com.devsrsouza.compose.icons:css-gg", version.ref = "composeicons" }
composeicons-evaicons = { module = "br.com.devsrsouza.compose.icons:eva-icons", version.ref = "composeicons" }
composeicons-feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "composeicons" }
composeicons-fontawesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeicons" }
composeicons-linea = { module = "br.com.devsrsouza.compose.icons:linea", version.ref = "composeicons" }
composeicons-lineawesome = { module = "br.com.devsrsouza.compose.icons:line-awesome", version.ref = "composeicons" }
composeicons-octicons = { module = "br.com.devsrsouza.compose.icons:octicons", version.ref = "composeicons" }
composeicons-simpleicons = { module = "br.com.devsrsouza.compose.icons:simple-icons", version.ref = "composeicons" }
composeicons-tablericons = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "composeicons" }
composeicons-weathericons = { module = "br.com.devsrsouza.compose.icons:erikflowers-weather-icons", version.ref = "composeicons" }

fresco = { module = "com.facebook.fresco:fresco", version.ref = "fresco" }
fresco-animated-gif = { module = "com.facebook.fresco:animated-gif", version.ref = "fresco" }
fresco-animated-webp = { module = "com.facebook.fresco:animated-webp", version.ref = "fresco" }
fresco-webpsupport = { module = "com.facebook.fresco:webpsupport", version.ref = "fresco" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler-kapt = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
glide-compiler-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }

javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

kotpref = { module = "com.chibatching.kotpref:kotpref", version.ref = "kotpref" }
kotpref-initializer = { module = "com.chibatching.kotpref:initializer", version.ref = "kotpref" }
kotpref-enums = { module = "com.chibatching.kotpref:enum-support", version.ref = "kotpref" }
kotpref-gson = { module = "com.chibatching.kotpref:gson-support", version.ref = "kotpref" }
kotpref-livedata = { module = "com.chibatching.kotpref:livedata-support", version.ref = "kotpref" }
kotpref-preferencescreendsl = { module = "com.chibatching.kotpref:preference-screen-dsl", version.ref = "kotpref" }

kradle-plugin-android = { module = "io.github.lyxnx.gradle:plugin-android", version.ref = "kradle" }
kradle-plugin-common = { module = "io.github.lyxnx.gradle:plugin-common", version.ref = "kradle" }
kradle-plugin-kotlin = { module = "io.github.lyxnx.gradle:plugin-kotlin", version.ref = "kradle" }
kradle-plugin-publishing = { module = "io.github.lyxnx.gradle:plugin-publish", version.ref = "kradle" }

landscapist = { module = "com.github.skydoves:landscapist", version.ref = "landscapist" }
landscapist-animation = { module = "com.github.skydoves:landscapist-animation", version.ref = "landscapist" }
landscapist-bom = { module = "com.github.skydoves:landscapist-bom", version.ref = "landscapist" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapist" }
landscapist-fresco = { module = "com.github.skydoves:landscapist-fresco", version.ref = "landscapist" }
landscapist-fresco-websupport = { module = "com.github.skydoves:landscapist-fresco-websupport", version.ref = "landscapist" }
landscapist-glide = { module = "com.github.skydoves:landscapist-glide", version.ref = "landscapist" }
landscapist-palete = { module = "com.github.skydoves:landscapist-palette", version.ref = "landscapist" }
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }
landscapist-transformation = { module = "com.github.skydoves:landscapist-transformation", version.ref = "landscapist" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

[plugins]
kradle-android-application = { id = "io.github.lyxnx.gradle.android-application", version.ref = "kradle" }
kradle-android-config = { id = "io.github.lyxnx.gradle.android-config", version.ref = "kradle" }
kradle-android-library = { id = "io.github.lyxnx.gradle.android-library", version.ref = "kradle" }

kradle-kotlin-config = { id = "io.github.lyxnx.gradle.kotlin-config", version.ref = "kradle" }
kradle-kotlin-library = { id = "io.github.lyxnx.gradle.kotlin-library", version.ref = "kradle" }

kradle-publishing = { id = "io.github.lyxnx.gradle.publishing", version.ref = "kradle" }

catalogs-compose-compiler-config = { id = "io.github.lyxnx.gradle.android.compose-compiler-config", version.ref = "catalogs-plugins" }
catalogs-compose-config = { id = "io.github.lyxnx.gradle.android.compose-config", version.ref = "catalogs-plugins" }
catalogs-firebase-config = { id = "io.github.lyxnx.gradle.android.firebase-config", version.ref = "catalogs-plugins" }
catalogs-hilt-config-kapt = { id = "io.github.lyxnx.gradle.android.hilt-config-kapt", version.ref = "catalogs-plugins" }
catalogs-hilt-config-ksp = { id = "io.github.lyxnx.gradle.android.hilt-config-ksp", version.ref = "catalogs-plugins" }
catalogs-room-config = { id = "io.github.lyxnx.gradle.android.room-config", version.ref = "catalogs-plugins" }
