[versions]
coil = "2.4.0"
composeicons = "1.1.0"

glide = "4.16.0"

lottie = "6.1.0"

kotlinpoet = "1.14.2"
kotpref = "2.13.2"

redmadrobot = "0.18.1"

catalogs-plugins = "2023.09.10"
kradle = "1.0.3"

[libraries]
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-compose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }

composeicons-cssgg = { module = "br.com.devsrsouza.compose.icons:css-gg", version.ref = "composeicons" }
composeicons-evaicons = { module = "br.com.devsrsouza.compose.icons:eva-icons", version.ref = "composeicons" }
composeicons-feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "composeicons" }
composeicons-fontawesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeicons" }
composeicons-linea = { module = "br.com.devsrsouza.compose.icons:linea", version.ref = "composeicons" }
composeicons-lineawesome = { module = "br.com.devsrsouza.compose.icons:line-awesome", version.ref = "composeicons" }
composeicons-octicons = { module = "br.com.devsrsouza.compose.icons:octicons", version.ref = "composeicons" }
composeicons-simpleicons = { module = "br.com.devsrsouza.compose.icons:simple-icons", version.ref = "composeicons" }
composeicons-tablericons = { module = "br.com.devsrsouza.compose.icons:tabler-icons", version.ref = "composeicons" }
composeicons-weathericons = { module = "br.com.devsrsouza.compose.icons:erikflowers-weather-icons", version.ref = "composeicons" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }

lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-compose = { module = "com.airbnb.android:lottie-compose", version.ref = "lottie" }

kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "kotlinpoet" }
kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "kotlinpoet" }

kotpref = { module = "com.chibatching.kotpref:kotpref", version.ref = "kotpref" }
kotpref-initializer = { module = "com.chibatching.kotpref:initializer", version.ref = "kotpref" }
kotpref-enums = { module = "com.chibatching.kotpref:enum-support", version.ref = "kotpref" }
kotpref-gson = { module = "com.chibatching.kotpref:gson-support", version.ref = "kotpref" }
kotpref-livedata = { module = "com.chibatching.kotpref:livedata-support", version.ref = "kotpref" }
kotpref-preferencescreendsl = { module = "com.chibatching.kotpref:preference-screen-dsl", version.ref = "kotpref" }

catalogs-androidplugins = { module = "io.github.lyxnx.gradle.android:android-plugins", version.ref = "catalogs-plugins" }

kradle-plugin-common = { module = "io.github.lyxnx.gradle:plugin-common", version.ref = "kradle" }
kradle-plugin-kotlin = { module = "io.github.lyxnx.gradle:plugin-kotlin", version.ref = "kradle" }
kradle-plugin-android = { module = "io.github.lyxnx.gradle:plugin-android", version.ref = "kradle" }

[plugins]
redmadrobot-android-application = { id = "com.redmadrobot.application", version.ref = "redmadrobot" }
redmadrobot-android-config = { id = "com.redmadrobot.android-config", version.ref = "redmadrobot" }
redmadrobot-android-library = { id = "com.redmadrobot.android-library", version.ref = "redmadrobot" }
redmadrobot-kotlin-library = { id = "com.redmadrobot.kotlin-library", version.ref = "redmadrobot" }
redmadrobot-publish = { id = "com.redmadrobot.publish", version.ref = "redmadrobot" }

catalogs-compose-config = { id = "io.github.lyxnx.gradle.android.compose-config", version.ref = "catalogs-plugins" }
catalogs-room-config = { id = "io.github.lyxnx.gradle.android.room-config", version.ref = "catalogs-plugins" }
catalogs-hilt-config = { id = "io.github.lyxnx.gradle.android.hilt-config", version.ref = "catalogs-plugins" }
catalogs-firebase-config = { id = "io.github.lyxnx.gradle.android.firebase-config", version.ref = "catalogs-plugins" }

kradle-android-config = { id = "io.github.lyxnx.gradle.android-config", version.ref = "kradle" }
kradle-android-application = { id = "io.github.lyxnx.gradle.android-application", version.ref = "kradle" }
kradle-android-library = { id = "io.github.lyxnx.gradle.android-library", version.ref = "kradle" }

kradle-kotlin-config = { id = "io.github.lyxnx.gradle.kotlin-config", version.ref = "kradle" }
kradle-kotlin-library = { id = "io.github.lyxnx.gradle.kotlin-library", version.ref = "kradle" }
